'use strict';
const questions={restaurant:[['organisation','Comment recevez-vous vos commandes à emporter et en livraison ?','Téléphone, site, plateformes, sur place…'],['frais','Que pensez-vous des commissions et frais que vous payez ?','Dites simplement ce qui vous convient ou vous gêne.'],['paiement','Comment encaissez-vous vos commandes aujourd’hui ?','Carte, espèces, lien de paiement…'],['frein','Qu’est-ce qui vous fait perdre le plus de temps ou de marge ?','Un exemple de votre quotidien suffit.'],['objectif','Qu’aimeriez-vous améliorer en priorité ?','Votre objectif pour les prochains mois.']],livreur:[['organisation','Comment trouvez-vous vos livraisons aujourd’hui ?','Applications, restaurants partenaires, clients directs…'],['frais','Comment êtes-vous rémunéré et quels frais vous sont prélevés ?','Avec vos mots, sans calcul compliqué.'],['paiement','Comment recevez-vous vos paiements aujourd’hui ?','Virement, espèces, plateforme…'],['frein','Quelle est votre principale difficulté au quotidien ?','Attente, distance, rémunération, organisation…'],['objectif','Qu’aimeriez-vous changer pour mieux travailler ?','Votre priorité pour les prochains mois.']]};
const form=document.querySelector('form'), area=document.querySelector('#questions'), result=document.querySelector('#result');
const drafts={restaurant:{},livreur:{}};let current='restaurant';
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
const profile=()=>form.elements.profil.value;
function render(){area.replaceChildren();for(const [id,label,hint] of questions[current]){const l=document.createElement('label');l.htmlFor=id;l.textContent=label;const t=document.createElement('textarea');t.id=id;t.name=id;t.maxLength=500;t.placeholder=hint;t.value=drafts[current][id]||'';area.append(l,t);}result.hidden=true;}
form.elements.profil.forEach(r=>r.addEventListener('change',()=>{for(const [id] of questions[current])drafts[current][id]=form.elements[id].value;current=profile();render();clearStatus();}));
function snapshot(){return Object.fromEntries(questions[profile()].map(([id])=>[id,form.elements[id].value.trim()]));}
function estimate(){const c=form.elements.cost.value;const price=Number(form.elements.plan.value);if(c==='')return `Formule ${price===99.99?'Start':'Pro'} : ${money(price)} HT / an. Indiquez vos frais mensuels pour obtenir un écart estimatif.`;const delta=Number(c)*12-price;return `Frais actuels déclarés : ${money(Number(c)*12)} HT / an. ZEROO : ${money(price)} HT / an. ${delta>=0?'Écart annuel potentiel en votre faveur':'Surcoût annuel estimé'} : ${money(Math.abs(delta))} HT.`;}
function compare(){if(!form.elements.cost.checkValidity()){form.elements.cost.reportValidity();return false;}const a=snapshot();const rows=[['Organisation',a.organisation,profile()==='restaurant'?'Click & collect et livraison : un modèle de mise en relation sans commission ZEROO.':'Mise en relation avec des restaurants et clients, sans commission ZEROO sur vos courses.'],['Frais de plateforme',a.frais,'Abonnement annuel : Start 99,99 € HT ou Pro 199,99 € HT.'],['Paiement',a.paiement,profile()==='restaurant'?'Vous utilisez vos propres coordonnées de paiement pour vos transactions.':'Vous utilisez vos propres coordonnées de paiement pour encaisser vos prestations.']];const tbody=document.querySelector('#comparison');tbody.replaceChildren();for(const row of rows){const tr=document.createElement('tr');row.forEach((v,i)=>{const cell=document.createElement(i===0?'th':'td');if(i===0)cell.scope='row';cell.textContent=v||'Non renseigné';tr.append(cell);});tbody.append(tr);}document.querySelector('#estimate').textContent=estimate();document.querySelector('#priority').textContent=a.objectif?`Votre priorité : ${a.objectif}. Notre retour permettra de vérifier si ZEROO répond à ce besoin.`:'Votre difficulté et votre objectif seront étudiés dans notre retour personnalisé.';result.hidden=false;return true;}
document.querySelector('#compare').addEventListener('click',()=>{if(compare()){result.focus();result.scrollIntoView({behavior:'smooth',block:'start'});}});
function report(){const a=snapshot();return ['DIAGNOSTIC ZEROO — '+(profile()==='restaurant'?'Restaurant':'Livreur indépendant'),'Nom : '+form.elements.name.value.trim(),'E-mail : '+form.elements.email.value.trim(),'Activité : '+form.elements.business.value.trim(),'Ville / zone : '+form.elements.city.value.trim(),'',...questions[profile()].map(([id,label])=>label+'\n'+(a[id]||'Non renseigné')+'\n'),'COMPARAISON INDICATIVE',estimate(),'Zéro commission ZEROO. Transactions avec vos propres coordonnées de paiement. Stripe réservé aux abonnements ZEROO.','Fonctionnalités par formule à préciser. À activité constante, si les frais déclarés sont intégralement remplacés. Hors frais de paiement et d’exploitation. Aucun gain net ni volume garanti.','','Je souhaite être recontacté au sujet de ce diagnostic.'].join('\n');}
function clearStatus(){document.querySelector('#status').textContent='';document.querySelector('#fallback').hidden=true;}
form.addEventListener('input',()=>{clearStatus();if(!result.hidden)compare();});
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;compare();const subject='Diagnostic ZEROO — '+(profile()==='restaurant'?'Restaurant':'Livreur');window.location.href='mailto:contact@aiworkpay.fr?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(report());document.querySelector('#status').textContent='E-mail préparé. Validez l’envoi dans votre messagerie. Si elle ne s’ouvre pas, copiez le diagnostic et envoyez-le à contact@aiworkpay.fr.';});
document.querySelector('#copy').addEventListener('click',async()=>{if(!form.reportValidity())return;const text=report();try{await navigator.clipboard.writeText(text);document.querySelector('#status').textContent='Diagnostic copié. Collez-le dans un e-mail à contact@aiworkpay.fr.';}catch{const t=document.querySelector('#fallback');t.value=text;t.hidden=false;t.focus();t.select();document.querySelector('#status').textContent='Copiez le texte ci-dessous et envoyez-le à contact@aiworkpay.fr.';}});
const requestedProfile=new URLSearchParams(window.location.search).get('profil');
if(requestedProfile==='restaurant'||requestedProfile==='livreur'){current=requestedProfile;form.querySelector('input[name=profil][value='+requestedProfile+']').checked=true;}
render();
